apiVersion: apps/v1
kind: Deployment
metadata:
  name: translation-microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: translation-microservice
  template:
    metadata:
      namespace: translation-microservice
      labels:
        app: translation-microservice
    spec:
      containers:
        - name: translation-microservice
          image: tkrikoriam/translation-microservice:tagname:v11
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: URL_TOKEN_AZURE
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: urltokenazure
            - name: URL_AZURE_TRANSLATE
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: azuretraductorurl
            - name: URL_AZURE_LANGUAGES_LIST
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: languageslist
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: azureAccessToken
